### ISSUE TITLE
Headline Arrows and Dots

### ISSUE THREAD

**Issue by Jmurray1018** [jcjordn5/onenewsstand#3]
In the Headline section, can you either eliminate the arrow when you reach the end of the section (ie if you're all the way left, the left arrow doesn't appear) or have it change color to the same light grey color as the "Top Stories" text.

Along with the arrows, can the dots change color to the blue that we use for the sources, indicating the page you're on (ie if you're on page 2 the 2nd dot should be blue). Also, move the dots up to be closer to the headlines section.

Thanks!

**Comment by turnerniles** [comment]
Implemented all requests. Dots are orange.
